tests: Use defaults.ini instead of isso.conf
Since commit 93e783ed606ce55a77104a4822269ceeb27c7f52
> symlink share/isso.conf to isso/defaults.ini and include it
> properly
Isso's internals look for `defaults.ini`, but the test suite
was overlooked.

---

For completeness' sake, this also fixes an eror when
developing:

`isso.conf` will not be available when packaged, while
`defaults.ini` will be part of the final package, which
nosetests utilizes.

Fixes:
```
pip install .
nosetests --with-doctest --with-coverage \
          --cover-package=isso isso/

[...]
======================================================================
ERROR: testZeroLikes (test_vote.TestVote)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/isso/isso/tests/test_vote.py", line 40, in testZeroLikes
    rv = self.makeClient("127.0.0.1").post(
  File "/home/user/isso/isso/tests/test_vote.py", line 26, in makeClient
    conf.set("general", "dbpath", self.path)
  File "/usr/lib/python3.9/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'general'
```
Isso is trying to read
`<venv>/site-packages/isso-0.12.3-py3.9.egg/share/isso.conf`
which does not exist.

NOTE: One could also "install" Isso in "editable" format via
`pip install -e .`, which will symlink the site-packages dir
to the current development dir.